apiVersion: v1
kind: Service
metadata:
  name: {{ include "custody-service.fullname" . }}
  labels:
    {{- include "custody-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: grpc
{{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
{{- end }}
  {{- range .Values.service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "custody-service.selectorLabels" . | nindent 4 }}
