{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "payments-orchestrator.fullname" . }}
  labels:
    {{- include "payments-orchestrator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "payments-orchestrator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
