{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aml-adapter.fullname" . }}
  labels:
    {{- include "aml-adapter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "aml-adapter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
{{- end }}
