{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "risk-engine.fullname" . }}
  labels:
    {{- include "risk-engine.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "risk-engine.selectorLabels" . | nindent 6 }}
{{- end }}
